fsm:
  flight_type: 2
  thresh_replan:  1.5 
  thresh_no_replan: 2.0
  planning_horizon: 7.5
  planning_horizen_time:  3
  emergency_time_:  1.0
  waypoint_num: 5
  waypoint0_x:  -15.0
  waypoint0_y:  0.0
  waypoint0_z:  1.0
  waypoint1_x:  0.0
  waypoint1_y:  15.0
  waypoint1_z:  1.0
  waypoint2_x:  15.0
  waypoint2_y:  0.0
  waypoint2_z:  1.0
  waypoint3_x:  0.0
  waypoint3_y:  -15.0
  waypoint3_z:  1.0
  waypoint4_x:  -15.0
  waypoint4_y:  0.0
  waypoint4_z:  1.0

grid_map:
  resolution: 0.1
  map_size_x: 40.0
  map_size_y: 40.0
  map_size_z: 3.0
  local_update_range_x: 5.5
  local_update_range_y: 5.5 
  local_update_range_z: 4.5
  obstacles_inflation:  0.099
  local_map_margin: 30
  ground_height:  -0.01
  cx: 321.046
  cy: 243.449
  fx: 387.229
  fy: 387.229
  use_depth_filter: true
  depth_filter_tolerance: 0.15
  depth_filter_maxdist: 5.0
  depth_filter_mindist: 0.2
  depth_filter_margin:  1
  k_depth_scaling_factor: 1000.0
  skip_pixel: 2
  p_hit:  0.65
  p_miss: 0.35
  p_min:  0.12
  p_max:  0.90
  p_occ:  0.80
  min_ray_length: 0.1
  max_ray_length: 4.5
  virtual_ceil_height:  2.5
  visualization_truncate_height:  2.4
  show_occ_time:  false
  pose_type:  2
  frame_id: "world"
  raycast_flag: true
  project_flag:  true
  visualize_flag:  true
  esdf_flag: false
  mapping_frequency: 20.0
  esdf_slice_height: 0.5



manager:
  max_vel:  2.0
  max_acc:  3.0
  max_jerk: 4.0
  control_points_distance:  0.4
  feasibility_tolerance:  0.05
  planning_horizon: 7.5

optimization:
  lambda_smooth:  1.0
  lambda_collision: 0.5
  lambda_feasibility: 0.1
  lambda_fitness: 1.0
  dist0:  0.5
  max_vel:  2.0
  max_acc:  3.0

bspline:
  limit_vel:  2.0
  limit_acc:  3.0
  limit_ratio:  1.1

